.travis.yml

Don't build the myriad of branches we could have

---

qmxgraph/page/fixes.js
qmxgraph/page/graph.html
qmxgraph/test_tools.py
tests/test_qt_js_integration.py

Also add a `get_cell_count` test helper function.

Fix `String.prototype.lastIndexOf` on Qt 5.6.2

---

qmxgraph/widget.py

Overwrite the `paintEvent` in `qmxgraph.widget.QmxGraph`

---

qmxgraph/api.py
qmxgraph/page/api.js
tests/conftest.py
tests/test_js_graph.py

Enable a decoration to be added to an edge without having details about the target edge.

Add `graphs.Api#insertDecorationOnEdge`

---

esss_environment.devenv.yml

In the old version it was possible to observe an issue when to display the widget was necessary scroll bars and when scrolled it was not possible to drag the connections.
Somewhere since that version and the most recent one this problems was solved in mxgraph.

Update mxgraph version on esss_environment.devenv.yml

---

qmxgraph/common_testing.py
tests/test_qt_js_integration.py

Add `qmxgraph.common_testing.get_cell_ids`

---

README.rst

Move codacy bage to the top along the other badges.

Move codacy badge

---

.travis.yml
qmxgraph/api.py
qmxgraph/page/api.js
qmxgraph/widget.py

New state of the graph and its scale/translation will be notified every time an UNDO event happens.

Add callback to update graph dump and scale and translation on Undo events

---

qmxgraph/api.py
qmxgraph/page/api.js
tests/test_qt_js_integration.py

ASIM-2204: Don't allow changes while project is paused

Add support to some mxGraph graph api calls

---

qmxgraph/api.py
qmxgraph/page/api.js
tests/test_qt_js_integration.py

Fb etk asim 1367 resume simulation

---

qmxgraph/constants.py
qmxgraph/mime.py
qmxgraph/widget.py
tests/test_qt_js_integration.py

Add "customAppDropEvent" to allow custom drag and drop handling.

Fb asim 2074 gas lift valve

---

qmxgraph/api.py
qmxgraph/page/api.js
tests/test_js_graph.py
tests/test_qt_js_integration.py

Fb asim 606 well editor

---

qmxgraph/api.py
qmxgraph/page/api.js
qmxgraph/page/graphs.js
qmxgraph/widget.py
tests/conftest.py
tests/test_js_graph.py
tests/test_qt_js_integration.py

Also allows to control port visibility.

Add terminal change event with port info

---

.github/workflows/main.yml
examples/drag_and_drop/main.py
qmxgraph/api.py
qmxgraph/cell_bounds.py
qmxgraph/decoration_contents.py
qmxgraph/page/api.js
qmxgraph/page/graphs.js
qmxgraph/page/utils.js
qmxgraph/widget.py
tests/test_decoration_contents.py

- Facilitates serialization of "table contents input";
- Allow external code to be notified by cell bounds changes;
- Allow to optionally define the "id" of a cell when creating;

Fb asim etk pyqt5 long lived prusse 2021 03 10 base

---

qmxgraph/page/api.js

Handle min and max position for edge decoration

---

environment.devenv.yml
qmxgraph/page/api.js

Merging alfasim 1.9.0 release branch back to master.

Fb asim v1.9.0 to master

---

qmxgraph/_web_view.py

As discussed in chat, this is an experiment to see if the random timeouts
we get on occasion in CI (probably not, but quick to try and see).

Increase eval_js timeout to 10s

---

qmxgraph/waiting.py
qmxgraph/widget.py
tests/test_qt_js_integration.py

[ASIM-4284](https://eden.esss.co/jira/browse/ASIM-4284)
[ASIM-4287](https://eden.esss.co/jira/browse/ASIM-4287)

Remove unused functions and other dead code

---

.github/workflows/main.yml
src/qmxgraph/_web_view.py
src/qmxgraph/api.py
src/qmxgraph/exceptions.py
src/qmxgraph/js.py
src/qmxgraph/widget.py
tests/test_qt_js_integration.py

This PR adds missing tests for functionality add/changed while porting to Qt 5.12.
The commits can be reviewed individually.
[ASIM-4282](https://eden.esss.co/jira/browse/ASIM-4282)
[ASIM-4283](https://eden.esss.co/jira/browse/ASIM-4283)
[ASIM-4285](https://eden.esss.co/jira/browse/ASIM-4285)

Add missing tests 

---

.pre-commit-config.yaml
.prettierrc
src/qmxgraph/page/api.js
src/qmxgraph/page/css/graph.css
src/qmxgraph/page/error_redirect.js
src/qmxgraph/page/fixes.js
src/qmxgraph/page/graphs.js
src/qmxgraph/page/mxextensions.js
src/qmxgraph/page/namespace.js
src/qmxgraph/page/standalone.js
src/qmxgraph/page/utils.js

Add prettier pre-commit hook to auto format JS

---

examples/drag_and_drop/main.py
src/qmxgraph/configuration.py
src/qmxgraph/page/api.js
src/qmxgraph/page/graphs.js
tests/test_qt_js_integration.py

Also fixes the `drag_and_drop` example.
https://user-images.githubusercontent.com/6764500/206485053-cc6020bf-b31e-47db-b438-0be871a81824.mp4

Add support for zooming in/out centered on the mouse cursor

---

.pre-commit-config.yaml

updates:
- [github.com/psf/black: 23.12.0 → 23.12.1](https://github.com/psf/black/compare/23.12.0...23.12.1)
- [github.com/pre-commit/mirrors-prettier: v4.0.0-alpha.7 → v4.0.0-alpha.8](https://github.com/pre-commit/mirrors-prettier/compare/v4.0.0-alpha.7...v4.0.0-alpha.8)
- [github.com/pre-commit/mirrors-mypy: v1.7.1 → v1.8.0](https://github.com/pre-commit/mirrors-mypy/compare/v1.7.1...v1.8.0)

Bring master to FB-ASIM-5088
